#DATABASE
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://awsrds.cnm1owomoyrd.ap-northeast-2.rds.amazonaws.com:3306/sstepdb?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: sstep
    password: sstep1234

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show-sql: true
        format-sql: true

server:
  port: 3306
